services:
  web:
    container_name: web
    build: .
    ports:
      - "80:80"
      - "443:443"
  mikuserv:
    container_name: mikuserv
    build: /home/tmiku/mikuserv/
    expose: # expose mikuserv to ngninx container, but no "ports" entry to external internet
      - 3001


